services:
  - type: web
    name: jukestream
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
